# build environment
FROM node:12.2.0-alpine as build
WORKDIR /app
# TODO change this to point to the repo
ENV PATH /Users/cwright/code/ReactPlay/node_modules/.bin:$PATH
COPY package.json /Users/cwright/code/ReactPlay/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent
RUN npm install redux react-redux
COPY . /app
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]